export const COUNTRY_FLAGS: Record<string, string> = {
  ARG: "🇦🇷",
  BRA: "🇧🇷",
  FRA: "🇫🇷",
  ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  GER: "🇩🇪",
  ESP: "🇪🇸",
  POR: "🇵🇹",
  NED: "🇳🇱",
  BEL: "🇧🇪",
  CRO: "🇭🇷",
  URU: "🇺🇾",
  DEN: "🇩🇰",
  SUI: "🇨🇭",
  POL: "🇵🇱",
  SRB: "🇷🇸",
  WAL: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  JPN: "🇯🇵",
  KOR: "🇰🇷",
  AUS: "🇦🇺",
  IRN: "🇮🇷",
  KSA: "🇸🇦",
  QAT: "🇶🇦",
  SEN: "🇸🇳",
  MAR: "🇲🇦",
  TUN: "🇹🇳",
  GHA: "🇬🇭",
  CMR: "🇨🇲",
  USA: "🇺🇸",
  CAN: "🇨🇦",
  MEX: "🇲🇽",
  CRC: "🇨🇷",
  ECU: "🇪🇨",
  ITA: "🇮🇹",
  COL: "🇨🇴",
  PAR: "🇵🇾",
  PER: "🇵🇪",
  CHI: "🇨🇱",
  VEN: "🇻🇪",
  NOR: "🇳🇴",
  SWE: "🇸🇪",
  TUR: "🇹🇷",
  HUN: "🇭🇺",
  AUT: "🇦🇹",
  EGY: "🇪🇬",
  NGA: "🇳🇬",
  CIV: "🇨🇮",
  ALG: "🇩🇿",
  NZL: "🇳🇿",
  RSA: "🇿🇦",
  CZE: "🇨🇿",
  SCO: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  CPV: "🇨🇻",
  COD: "🇨🇩",
  CUW: "🇨🇼",
  HAI: "🇭🇹",
  IRQ: "🇮🇶",
  JOR: "🇯🇴",
  UZB: "🇺🇿",
  PAN: "🇵🇦",
  BIH: "🇧🇦",
};

export function flagOf(code: string): string {
  return COUNTRY_FLAGS[code] ?? "🏳️";
}

export const FLAG_SLUGS: Record<string, string> = {
  ARG: "ar",
  BRA: "br",
  FRA: "fr",
  ENG: "gb-eng",
  GER: "de",
  ESP: "es",
  POR: "pt",
  NED: "nl",
  BEL: "be",
  CRO: "hr",
  URU: "uy",
  DEN: "dk",
  SUI: "ch",
  POL: "pl",
  SRB: "rs",
  WAL: "gb-wls",
  JPN: "jp",
  KOR: "kr",
  AUS: "au",
  IRN: "ir",
  KSA: "sa",
  QAT: "qa",
  SEN: "sn",
  MAR: "ma",
  TUN: "tn",
  GHA: "gh",
  CMR: "cm",
  USA: "us",
  CAN: "ca",
  MEX: "mx",
  CRC: "cr",
  ECU: "ec",
  ITA: "it",
  COL: "co",
  PAR: "py",
  PER: "pe",
  CHI: "cl",
  VEN: "ve",
  NOR: "no",
  SWE: "se",
  TUR: "tr",
  HUN: "hu",
  AUT: "at",
  EGY: "eg",
  NGA: "ng",
  CIV: "ci",
  ALG: "dz",
  NZL: "nz",
  RSA: "za",
  CZE: "cz",
  SCO: "gb-sct",
  CPV: "cv",
  COD: "cd",
  CUW: "cw",
  HAI: "ht",
  IRQ: "iq",
  JOR: "jo",
  UZB: "uz",
  PAN: "pa",
  BIH: "ba",
};

type FlagWidth = 40 | 80 | 160 | 320 | 640 | 1280;

export function flagUrl(code: string, width: FlagWidth = 160): string | null {
  const slug = FLAG_SLUGS[code];
  if (!slug) return null;
  return `https://flagcdn.com/w${width}/${slug}.png`;
}
