import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const ENV_PATH = resolve(ROOT, ".env.local");
const OUT_PATH = resolve(ROOT, "lib/mock/squads.ts");
const REQ_GAP_MS = 7000;
const RETRY_WAIT_MS = 65_000;

function loadEnv() {
  const text = readFileSync(ENV_PATH, "utf8");
  for (const line of text.split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}
loadEnv();

const API_KEY = process.env.API_FOOTBALL_KEY;
if (!API_KEY) {
  console.error("Missing API_FOOTBALL_KEY in .env.local");
  process.exit(1);
}

const BASE = "https://v3.football.api-sports.io";
const HEADERS = { "x-apisports-key": API_KEY };

const COUNTRIES = [
  { code: "ARG", name: "Argentina", teamId: 26 },
  { code: "BRA", name: "Brazil", teamId: 6 },
  { code: "FRA", name: "France", teamId: 2 },
  { code: "ENG", name: "England", teamId: 10 },
  { code: "GER", name: "Germany", teamId: 25 },
  { code: "ESP", name: "Spain", teamId: 9 },
  { code: "POR", name: "Portugal", teamId: 27 },
  { code: "NED", name: "Netherlands", teamId: 1118 },
  { code: "BEL", name: "Belgium", teamId: 1 },
  { code: "CRO", name: "Croatia", teamId: 3 },
  { code: "URU", name: "Uruguay", teamId: 7 },
  { code: "DEN", name: "Denmark", teamId: 21 },
  { code: "SUI", name: "Switzerland", teamId: 15 },
  { code: "POL", name: "Poland", teamId: 24 },
  { code: "SRB", name: "Serbia", teamId: 14 },
  { code: "WAL", name: "Wales", teamId: 767 },
  { code: "JPN", name: "Japan", teamId: 12 },
  { code: "KOR", name: "South-Korea", teamId: 17 },
  { code: "AUS", name: "Australia", teamId: 20 },
  { code: "IRN", name: "Iran", teamId: 22 },
  { code: "KSA", name: "Saudi-Arabia", teamId: 23 },
  { code: "QAT", name: "Qatar", teamId: 1569 },
  { code: "SEN", name: "Senegal", teamId: 13 },
  { code: "MAR", name: "Morocco", teamId: 31 },
  { code: "TUN", name: "Tunisia", teamId: 28 },
  { code: "GHA", name: "Ghana", teamId: 1504 },
  { code: "CMR", name: "Cameroon", teamId: 1530 },
  { code: "USA", name: "USA", teamId: 2384 },
  { code: "CAN", name: "Canada", teamId: 5529 },
  { code: "MEX", name: "Mexico", teamId: 16 },
  { code: "CRC", name: "Costa-Rica", teamId: 29 },
  { code: "ECU", name: "Ecuador", teamId: 2382 },
  { code: "ITA", name: "Italy" },
  { code: "COL", name: "Colombia" },
  { code: "PAR", name: "Paraguay" },
  { code: "PER", name: "Peru" },
  { code: "CHI", name: "Chile" },
  { code: "VEN", name: "Venezuela" },
  { code: "NOR", name: "Norway" },
  { code: "SWE", name: "Sweden" },
  { code: "TUR", name: "Türkiye", teamId: 777 },
  { code: "HUN", name: "Hungary" },
  { code: "AUT", name: "Austria" },
  { code: "EGY", name: "Egypt" },
  { code: "NGA", name: "Nigeria" },
  { code: "CIV", name: "Ivory-Coast" },
  { code: "ALG", name: "Algeria" },
  { code: "NZL", name: "New-Zealand" },
];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function jget(url, attempt = 1) {
  const r = await fetch(url, { headers: HEADERS });
  if (r.status === 429) {
    if (attempt > 3) throw new Error(`429 after ${attempt} tries`);
    console.log(`  …rate-limited, sleeping ${RETRY_WAIT_MS / 1000}s`);
    await sleep(RETRY_WAIT_MS);
    return jget(url, attempt + 1);
  }
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.json();
}

async function resolveTeamId(name) {
  const q = name.replace(/-/g, " ");
  const d = await jget(`${BASE}/teams?search=${encodeURIComponent(q)}`);
  const match = (d.response ?? []).find(
    (t) => t.team?.national === true && t.team?.name?.toLowerCase() === q.toLowerCase(),
  );
  return match?.team?.id ?? null;
}

async function fetchSquad(teamId) {
  const d = await jget(`${BASE}/players/squads?team=${teamId}`);
  const entry = d.response?.[0];
  if (!entry) return null;
  return {
    team: { id: entry.team.id, name: entry.team.name, logo: entry.team.logo },
    players: entry.players.map((p) => ({
      id: p.id,
      number: p.number,
      position: p.position,
      name: p.name,
      age: p.age,
      photo: p.photo,
    })),
  };
}

function loadExisting() {
  if (!existsSync(OUT_PATH)) return {};
  const text = readFileSync(OUT_PATH, "utf8");
  const m = text.match(/=\s*({[\s\S]*});\s*$/);
  if (!m) return {};
  try {
    return JSON.parse(m[1]);
  } catch {
    return {};
  }
}

function serialise(map) {
  const header =
    `// AUTO-GENERATED by scripts/fetch-squads.mjs — do not edit by hand.\n` +
    `// Run \`node scripts/fetch-squads.mjs\` to refresh.\n\n` +
    `import type { Squad } from "@/types";\n\n` +
    `export const SQUADS: Record<string, Squad> = `;
  const body = JSON.stringify(map, null, 2);
  return `${header}${body};\n`;
}

async function main() {
  const out = loadExisting();
  const alreadyHave = new Set(Object.keys(out));
  if (alreadyHave.size) console.log(`resuming — already have: ${[...alreadyHave].join(", ")}`);

  let calls = 0;
  for (const c of COUNTRIES) {
    if (alreadyHave.has(c.code)) continue;
    try {
      let teamId = c.teamId;
      if (!teamId) {
        teamId = await resolveTeamId(c.name);
        calls += 1;
        await sleep(REQ_GAP_MS);
        if (!teamId) {
          console.warn(`skip ${c.code} (${c.name}) — no national team found`);
          continue;
        }
        console.log(`resolved ${c.code} -> ${teamId}`);
      }
      const squad = await fetchSquad(teamId);
      calls += 1;
      if (!squad) {
        console.warn(`skip ${c.code} — empty squad`);
      } else {
        out[c.code] = {
          code: c.code,
          country: c.name.replace(/-/g, " "),
          teamId,
          teamName: squad.team.name,
          logo: squad.team.logo,
          players: squad.players,
        };
        console.log(`ok   ${c.code} (${squad.players.length} players)`);
        writeFileSync(OUT_PATH, serialise(out));
      }
      await sleep(REQ_GAP_MS);
    } catch (e) {
      console.error(`fail ${c.code}:`, e.message);
      writeFileSync(OUT_PATH, serialise(out));
    }
  }
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, serialise(out));
  console.log(`\nwrote ${OUT_PATH}`);
  console.log(`new api calls this run: ${calls}; total squads stored: ${Object.keys(out).length}`);
}

main();
